In [1]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
a = np.diag([1, 2, 3, 4, 5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [2]:
#Create a 3x3x3 array with random values
import numpy as np
b = np.random.random((3,3,3))
print(b)

[[[0.17151836 0.76999084 0.12589278]
  [0.31180954 0.44584996 0.82490299]
  [0.44123761 0.00342391 0.15982413]]

 [[0.0685147  0.82001753 0.44673732]
  [0.86866038 0.23422161 0.55849842]
  [0.7301325  0.45425372 0.12938286]]

 [[0.92632283 0.865761   0.26340635]
  [0.5745461  0.3490399  0.19180275]
  [0.21323626 0.19549509 0.09347104]]]


In [4]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
c = np.ones((3,3))
c = np.zeros((8,8),dtype=int)
c[1::2,::2] = 1
c[::2,1::2] = 1
print("pattern")
print(c)

pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#Normalize a 5x5 random matrix
d= np.random.random((3,3))
print("before normalization")
print(d)
dmax, dmin = d.max(), d.min()
d = (d - dmin)/(dmax - dmin)
print("after normalization")
print(d)

before normalization
[[0.63732149 0.36271909 0.78563408]
 [0.63305703 0.06507382 0.41995079]
 [0.6567812  0.56245007 0.77150632]]
after normalization
[[0.79417047 0.41307478 1.        ]
 [0.78825221 0.         0.49250144]
 [0.82117682 0.69026322 0.98039337]]


In [7]:
#How to find common values between two arrays?
arr_1 = np.array([0, 10, 40, 60])
print(arr_1)
arr_2 = [0, 30, 40]
print(arr_2)
print("Common values between two arrays")
print(np.intersect1d(arr_1, arr_2))

[ 0 10 40 60]
[0, 30, 40]
Common values between two arrays
[ 0 40]


In [8]:
#How to get the dates of yesterday, today and tomorrow?
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday date is ",y)
today = np.datetime64('today', 'D')
print("Today's date is ",today)
tmrrw  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is ",tmrrw)

Yestraday date is  2020-07-27
Today's date is  2020-07-28
Tomorrow's date is  2020-07-29


In [13]:
#Consider two random array A and B, check if they are equal
x = np.random.randint(0,1,2)
print("First array:")
print(x)
y = np.random.randint(0,1,2)
print("Second array:")
print(y)
array_equal = np.allclose(x,y)
print("The two arrays are",array_equal)

First array:
[0 0]
Second array:
[0 0]
The two arrays are True


In [14]:
#Create random vector of size 10 and replace the maximum value by 0
g = np.random.random(10)
print(g)
g[g.argmax()] = 0
print("replaced vector =")
print(g)

[0.89302268 0.02593541 0.16245411 0.88427156 0.09168993 0.10543718
 0.03310005 0.75910952 0.37281969 0.91824097]
replaced vector =
[0.89302268 0.02593541 0.16245411 0.88427156 0.09168993 0.10543718
 0.03310005 0.75910952 0.37281969 0.        ]


In [17]:
#How to print all the values of an array?
myarr = np.arange(10)
np.set_printoptions(threshold=np.inf)
print(myarr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#Subtract the mean of each row of a matrix
X = np.random.rand(5, 5)
print(X)
print("\n subracted mean matrix")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.22824656 0.42188277 0.47071758 0.84221744 0.41760812]
 [0.56677184 0.42021395 0.2038501  0.25545275 0.34454335]
 [0.77480445 0.12234824 0.80305382 0.10444367 0.96988205]
 [0.7930341  0.27421677 0.25864127 0.53195236 0.44853426]
 [0.78041185 0.17524423 0.05231458 0.61985602 0.50164093]]

 subracted mean matrix
[[-0.24788794 -0.05425173 -0.00541691  0.36608294 -0.05852637]
 [ 0.20860544  0.06204755 -0.1543163  -0.10271365 -0.01362305]
 [ 0.219898   -0.4325582   0.24814737 -0.45046277  0.41497561]
 [ 0.33175835 -0.18705898 -0.20263448  0.07067661 -0.01274149]
 [ 0.35451833 -0.25064929 -0.37357894  0.1939625   0.07574741]]
